


source =~/.config/hypr/modules/io.conf
source =~/.config/hypr/modules/generals.conf
source =~/.config/hypr/modules/autostart.conf
source =~/.config/hypr/modules/env.conf
source =~/.config/hypr/modules/windowrules.conf
source =~/.config/hypr/modules/plugins.conf
source =~/.config/hypr/modules/decorations.conf
source =~/.config/hypr/modules/bindings.conf



