-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


-- exec-once = hyprpm reload &




-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet &")
    hl.exec_cmd("waybar & swaync & awww-daemon &")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("systemctl --user start hyprpolkitagent &")
end)
