-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 7,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = false,
            xray = false,
            noise = 0.02,
            vibrancy = 0.0,
            vibrancy_darkness = 0.5,
        },
    },
})

hl.config({
    animations = {
        enabled =  true 
    },
})
