-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("PATH", "/home/maady/.local/bin:/usr/local/bin:/usr/bin:/home/maady/bin")

hl.env("WLR_NO_HARDWARE_CURSOR", 1)

hl.env("LIBVA_DRIVER_NAME", "iHD")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "mesa")

hl.config({
    debug = {
        disable_logs = false,
        enable_stdout_logs = true,
    },
})

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
