-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 2,
        resize_on_border = true,
        allow_tearing = true,
        layout = "master",
        col = {
            active_border = "rgb(33ccff)",
            inactive_border = "rgb(595959)",
        },
    },
})

hl.config({
    misc = {
        force_default_wallpaper = 1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
    },
})

hl.config({
    opengl = {
        nvidia_anti_flicker = true,
    },
})
