
monitor=eDP-1,1920x1080,auto,1.25
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = ctrl:swapcaps
    kb_rules =
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    repeat_delay = 200
    repeat_rate = 25
    touchpad {
        natural_scroll = true
    }
}
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
xwayland {
  force_zero_scaling = true
}
