-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- plugin {

--     hyprscrolling {

--         column_width = 0.8

--         fullscreen_on_one_column = true 

--         follow_focus = true

--         focus_fit_method = 1

--     }

-- }
